In [1]:
import pandas as pd
from glob import glob
import libarchive # `pip install libarchive-c` and using with libarchive 3.4.x
from io import BytesIO

In [2]:
total_size = 0
header = True
for fn in sorted(glob('*.7z')):
    print(fn)
    with libarchive.file_reader(fn) as e:
        for entry in e:
            if not entry.isfile:
                continue
            total_size += entry.size
            print(entry.name, total_size / (1024*1024))
            with BytesIO() as f:
                for i, block in enumerate(entry.get_blocks()):
                    f.write(block)
                f.seek(0)
                #df = pd.read_csv(f, nrows=10, delimiter='\t', header=None, usecols=[2, 4, 19, 20])
                df = pd.read_csv(f, delimiter='\t', header=None, usecols=[2, 4, 19, 20])
            df.columns = ['last_name', 'first_name', 'gender', 'race']
            df.to_csv('/opt/data/fl_voter/fl_voter_name_gender_race.csv', mode='a', header=header, index=False)
            header = False

20170207_VoterDetail.7z
20170207_VoterDetail/ALA_20170207.txt 29.292259216308594
20170207_VoterDetail/BAK_20170207.txt 31.640080451965332
20170207_VoterDetail/BAY_20170207.txt 51.27226448059082
20170207_VoterDetail/BRA_20170207.txt 53.74375057220459
20170207_VoterDetail/BRE_20170207.txt 119.11902141571045
20170207_VoterDetail/BRO_20170207.txt 310.09432792663574
20170207_VoterDetail/CAL_20170207.txt 311.40102672576904
20170207_VoterDetail/CHA_20170207.txt 331.9234809875488
20170207_VoterDetail/CIT_20170207.txt 348.43804264068604
20170207_VoterDetail/CLA_20170207.txt 371.96534156799316
20170207_VoterDetail/CLL_20170207.txt 406.0159959793091
20170207_VoterDetail/CLM_20170207.txt 412.04163455963135
20170207_VoterDetail/DAD_20170207.txt 631.8463592529297
20170207_VoterDetail/DES_20170207.txt 634.3178129196167
20170207_VoterDetail/DIX_20170207.txt 635.8692283630371
20170207_VoterDetail/DUV_20170207.txt 732.8321886062622
20170207_VoterDetail/ESC_20170207.txt 766.6300640106201
20170207_VoterDetail/FLA_20170207.txt 779.0231113433838
20170207_VoterDetail/FRA_20170207.txt 780.2824745178223
20170207_VoterDetail/GAD_20170207.txt 784.6675453186035
20170207_VoterDetail/GIL_20170207.txt 786.3906574249268
20170207_VoterDetail/GLA_20170207.txt 787.6066637039185
20170207_VoterDetail/GUL_20170207.txt 789.2000017166138
20170207_VoterDetail/HAM_20170207.txt 790.476863861084
20170207_VoterDetail/HAR_20170207.txt 792.5194969177246
20170207_VoterDetail/HEN_20170207.txt 795.3739643096924
20170207_VoterDetail/HER_20170207.txt 816.2905158996582
20170207_VoterDetail/HIG_20170207.txt 826.1917791366577
20170207_VoterDetail/HIL_20170207.txt 959.8866882324219
20170207_VoterDetail/HOL_20170207.txt 961.5880575180054
20170207_VoterDetail/IND_20170207.txt 978.4171915054321
20170207_VoterDetail/JAC_20170207.txt 982.7562532424927
20170207_VoterDetail/JEF_20170207.txt 984.1736707687378
20170207_VoterDetail/LAF_20170207.txt 984.8291969299316
20170207_VoterDetail/LAK_20170207.txt 1017.4748048782349
20170207_VoterDetail/LEE_20170207.txt 1091.3626956939697
20170207_VoterDetail/LEO_20170207.txt 1124.4955854415894
20170207_VoterDetail/LEV_20170207.txt 1128.6503267288208
20170207_VoterDetail/LIB_20170207.txt 1129.35680103302
20170207_VoterDetail/MAD_20170207.txt 1131.2379331588745
20170207_VoterDetail/MAN_20170207.txt 1168.659688949585
20170207_VoterDetail/MON_20170207.txt 1178.138653755188
20170207_VoterDetail/MRN_20170207.txt 1213.4200582504272
20170207_VoterDetail/MRT_20170207.txt 1230.4996767044067
20170207_VoterDetail/NAS_20170207.txt 1240.2789793014526
20170207_VoterDetail/OKA_20170207.txt 1262.3098163604736
20170207_VoterDetail/OKE_20170207.txt 1265.3208875656128
20170207_VoterDetail/ORA_20170207.txt 1385.5390720367432
20170207_VoterDetail/OSC_20170207.txt 1418.8044681549072
20170207_VoterDetail/PAL_20170207.txt 1568.3288040161133
20170207_VoterDetail/PAS_20170207.txt 1623.5615692138672
20170207_VoterDetail/PIN_20170207.txt 1727.3045721054077
20170207_VoterDetail/POL_20170207.txt 1790.2020425796509
20170207_VoterDetail/PUT_20170207.txt 1797.4803819656372
20170207_VoterDetail/SAN_20170207.txt 1817.6592750549316
20170207_VoterDetail/SAR_20170207.txt 1863.0826930999756
20170207_VoterDetail/SEM_20170207.txt 1906.6497440338135
20170207_VoterDetail/STJ_20170207.txt 1934.9651346206665
20170207_VoterDetail/STL_20170207.txt 1967.3346490859985
20170207_VoterDetail/SUM_20170207.txt 1981.9009437561035
20170207_VoterDetail/SUW_20170207.txt 1985.817211151123
20170207_VoterDetail/TAY_20170207.txt 1987.6660499572754
20170207_VoterDetail/UNI_20170207.txt 1988.768856048584
20170207_VoterDetail/VOL_20170207.txt 2047.3908910751343
20170207_VoterDetail/WAK_20170207.txt 2050.4972190856934
20170207_VoterDetail/WAL_20170207.txt 2058.0556240081787
20170207_VoterDetail/WAS_20170207.txt 2060.3557147979736

In [3]:
df = pd.read_csv('/opt/data/fl_voter/fl_voter_name_gender_race.csv')
df

            last_name first_name gender  race
0              Walker  Elizabeth      F     5
1              Palmer      Alton      M     5
2            Mc Cleod     Alicia      F     3
3         Scarborough       Dale      M     5
4              Walker     Daniel      M     5
...               ...        ...    ...   ...
13710353      Walters    William      M     5
13710354       Sawyer    Matthew      M     5
13710355       Thomas     Janine      F     5
13710356     Campbell      Angel      F     7
13710357       Bruner        Jeb      M     5

[13710358 rows x 4 columns]